# Documentation
The database consists of multiple tables with multiple columns. For each table and column, in the database there is a comment stored, explaining in more detail the meaning and use of it.

### I have a column name what does it mean?

In [3]:
import evaluation.utils.db as db

col_name = 'E_WE__VvsRHE' # type here th ename of the column you need information for

doc_table = db.query_sql(''' SELECT * FROM documentation_columns WHERE name_column = %s''',
                         params=[col_name],
                         index_col=['name_column', 'name_table']
                        )
display(doc_table.drop_duplicates().groupby(level=0).first().style.set_properties(**{
    'text-align': 'left',
    'white-space': 'pre-wrap',
}))

### The value of the column is calculated by a view. What is the definition of the View?

In [3]:
import evaluation.utils.db as db
import sqlparse

name_view = 'data_icpms_sfc_analysis'

sql_create_view = db.get_create_view(name_view)
print(sqlparse.format(sql_create_view, reindent=True, keyword_case='upper'))

CREATE ALGORITHM=UNDEFINED DEFINER=`hte_root`@`%` SQL SECURITY DEFINER VIEW `data_icpms_sfc_analysis` AS
SELECT `di`.`id_exp_icpms` AS `id_exp_icpms`,
       `di`.`name_isotope_analyte` AS `name_isotope_analyte`,
       `di`.`name_isotope_internalstandard` AS `name_isotope_internalstandard`,
       `di`.`id_data_icpms` AS `id_data_icpms`,
       `di`.`t__s` AS `t__s`,
       `di`.`counts_analyte` AS `counts_analyte`,
       `di`.`counts_internalstandard` AS `counts_internalstandard`,
       `di_fit`.`counts_internalstandard_fitted` AS `counts_internalstandard_fitted`,
       `exp_icpms_sfc_expanded`.`name_setup_sfc` AS `name_setup_sfc`,
       (`exp_icpms_sfc_expanded`.`t_start__timestamp_sfc_pc` + interval `di`.`t__s` SECOND) AS `t__timestamp_sfc_pc`,
       ((`exp_icpms_sfc_expanded`.`t_start__timestamp_sfc_pc` + interval `di`.`t__s` SECOND) - interval `exp_icpms_sfc_expanded`.`t_delay__s` SECOND) AS `t_delaycorrected__timestamp_sfc_pc`,
       (`di`.`counts_analyte` / `di_fit`.`counts_internalstandard_fitted`) AS `a_is__countratio`,
       (((`di`.`counts_analyte` / `di_fit`.`counts_internalstandard_fitted`) - `exp_icpms_sfc_expanded`.`calibration_intercept__countratio`) / `exp_icpms_sfc_expanded`.`calibration_slope__countratio_mug_L`) AS `c_a__mug_L`,
       (((((`di`.`counts_analyte` / `di_fit`.`counts_internalstandard_fitted`) - `exp_icpms_sfc_expanded`.`calibration_intercept__countratio`) / `exp_icpms_sfc_expanded`.`calibration_slope__countratio_mug_L`) * `exp_icpms_sfc_expanded`.`flow_rate_real__mul_min`) / (1000 * 60)) AS `dm_dt__ng_s`
FROM ((`data_icpms` `di`
       LEFT JOIN `data_icpms_internalstandard_fitting` `di_fit` on(((`di`.`id_exp_icpms` = `di_fit`.`id_exp_icpms`)
                                                                    AND (`di`.`name_isotope_analyte` = `di_fit`.`name_isotope_analyte`)
                                                                    AND (`di`.`name_isotope_internalstandard` = `di_fit`.`name_isotope_internalstandard`)
                                                                    AND (`di`.`id_data_icpms` = `di_fit`.`id_data_icpms`))))
      JOIN `exp_icpms_sfc_expanded` on(((`di`.`id_exp_icpms` = `exp_icpms_sfc_expanded`.`id_exp_icpms`)
                                        AND (`di`.`name_isotope_analyte` = `exp_icpms_sfc_expanded`.`name_isotope_analyte`)
                                        AND (`di`.`name_isotope_internalstandard` = `exp_icpms_sfc_expanded`.`name_isotope_internalstandard`))))

### I want to read documentation of all tables and columns

In [9]:
import evaluation.utils.db as db
from IPython.display import display, Markdown
doc_table = db.query_sql(''' SELECT * FROM documentation_tables''',
                         index_col=['name_table']
                        )
for name_table, row in doc_table.iterrows():
    doc_cols = db.query_sql(''' SELECT name_column, name_inserter, comment, name_axislabel__latex, data_type FROM documentation_columns WHERE name_table = %s''',
                            params=[name_table],
                         index_col=['name_column']
                        )
    display(Markdown(
    f"""### {name_table}
        Table type: {row.table_type}
        Comment: {row.comment_table}
    """))
    #display(doc_cols)
    display(doc_cols.drop_duplicates().groupby(level=0).first().style.set_properties(**{
    'text-align': 'left',
    'white-space': 'pre-wrap',
    }))

### ana_deconvolution
        Table type: BASE TABLE
        Comment: list of experiments with performed deconvolution analysis.

### ana_deconvolution_calibration_data
        Table type: BASE TABLE
        Comment: response data for each calibration set defined in ana_deconvolution_calibration_set.

### ana_deconvolution_calibration_set
        Table type: BASE TABLE
        Comment: defines parameter used during a calibration routine required for later deconvolution analysis. Corresponding repsonse data is stored in ana_deconvolution_calibration_data

### ana_deconvolution_data
        Table type: BASE TABLE
        Comment: deconvoluted data for each analyzed experiment as defined in ana_deconvolution.

### ana_icpms_sfc_fitting
        Table type: BASE TABLE
        Comment: Stores results from sfc icpms fits as performed by Fit_SFC_ICP_MS_Dissolution.py

### ana_icpms_sfc_fitting_peaks
        Table type: BASE TABLE
        Comment: Stores details of peaks for fits in exp_icpms_sfc_peaks

### ana_integrations
        Table type: BASE TABLE
        Comment: stores all integration data

### counter_electrodes
        Table type: BASE TABLE
        Comment: Inventory list of avaiable counter electrode types. Different CEs of the same type are treated as one entry.

### data_compression
        Table type: BASE TABLE
        Comment: Contains compression data measured in compression experiments

### data_ec
        Table type: BASE TABLE
        Comment: Data table of all electrochemal direct current experiments identified by id_exp_ec

### data_ec_analysis
        Table type: VIEW
        Comment: VIEW

### data_ec_polcurve
        Table type: BASE TABLE
        Comment: averaged data of polarization curve experiments

### data_ec_polcurve_analysis
        Table type: VIEW
        Comment: VIEW

### data_eis
        Table type: BASE TABLE
        Comment: Data table of all electrochemical impedance spectroscopy experiments identified by id_exp_ec

### data_eis_analysis
        Table type: VIEW
        Comment: VIEW

### data_icpms
        Table type: BASE TABLE
        Comment: Data for all icp_ms experiments. Table stores one analyte-internal standard relationship per time step. If multiple analyte-internalstandard relations are measured they will produce multiple rows.

### data_icpms_internalstandard_fitting
        Table type: BASE TABLE
        Comment: Data for all icp_ms experiments. Table stores one analyte-internal standard relationship per time step. If multiple analyte-internalstandard relations are measured they will produce multiple rows.

### data_icpms_sfc_analysis
        Table type: VIEW
        Comment: VIEW

### data_icpms_sfc_analysis_no_istd_fitting
        Table type: VIEW
        Comment: VIEW

### data_icpms_sfc_analysis_old
        Table type: VIEW
        Comment: VIEW

### data_icpms_sfc_batch_analysis
        Table type: VIEW
        Comment: VIEW

### data_stability_analysis
        Table type: VIEW
        Comment: VIEW

### data_stability_batch_analysis
        Table type: VIEW
        Comment: VIEW

### documentation_columns
        Table type: VIEW
        Comment: VIEW

### documentation_tables
        Table type: VIEW
        Comment: VIEW

### dummy_data_icpms_sfc_batch_analysis
        Table type: BASE TABLE
        Comment: required for view data_icpms_sfc_batch_analysis

### ec_reactions
        Table type: BASE TABLE
        Comment: holding informations for electrochemical reactions

### electrolytes
        Table type: BASE TABLE
        Comment: Inventory list of available electrolyte salts

### elements
        Table type: BASE TABLE
        Comment: holding information of elements of periodic table

### exp_compression
        Table type: BASE TABLE
        Comment: parameter of compression experiments performed with sfc table

### exp_compression_expanded
        Table type: VIEW
        Comment: VIEW

### exp_ec
        Table type: BASE TABLE
        Comment: parameter of electrochemical experiments. For parameters which can hold more than one value per experiment (for instance multiple gas flows in one experiment) are located in other tables connected to the exp_ec table via the id_exp_ec. Same holds true for different ec techniques such as CV, PEIS , GEIS,... with technique specific parameters. All parameters combined in one table can be found in the corresponding view "exp_ec_expanded". It is recommended to use this one for selecting data to circumvent multiple join statements in the select query.

### exp_ec_cv
        Table type: BASE TABLE
        Comment: technique specific parameters for cyclic voltammetry (CV)

### exp_ec_datasets
        Table type: BASE TABLE
        Comment: table of all ec datasets

### exp_ec_datasets_definer
        Table type: BASE TABLE
        Comment: one ec dataset can consist of multiple exp_ec. This table is defining the n-n relationship

### exp_ec_expanded
        Table type: VIEW
        Comment: VIEW

### exp_ec_expanded_old
        Table type: VIEW
        Comment: VIEW

### exp_ec_geis
        Table type: BASE TABLE
        Comment: technique specific parameters for galvanostatic electrochemical impedance spectroscopy (GEIS)

### exp_ec_ghold
        Table type: BASE TABLE
        Comment: technique specific parameters for galvanostatic hold (GHOLD), also called one step chronopotentiometry

### exp_ec_gpulse
        Table type: BASE TABLE
        Comment: technique specific parameters for galvanostatic Pulse technique

### exp_ec_integration
        Table type: BASE TABLE
        Comment: all information from integration of ec data integration

### exp_ec_integration_expanded
        Table type: VIEW
        Comment: VIEW

### exp_ec_ocp
        Table type: BASE TABLE
        Comment: technique specific parameters for open circuit potential (OCP)

### exp_ec_peis
        Table type: BASE TABLE
        Comment: technique specific parameters for potentiostatic electrochemical impedance spectroscopy (PEIS)

### exp_ec_phold
        Table type: BASE TABLE
        Comment: technique specific parameters for galvanostatic hold (PHOLD), also called one step chronoamperometry

### exp_ec_polcurve
        Table type: BASE TABLE
        Comment: experimental information for polarization curve experiments. (Combination of geis and ghold)

### exp_ec_polcurve_expanded
        Table type: VIEW
        Comment: VIEW

### exp_ec_ppulse
        Table type: BASE TABLE
        Comment: technique specific parameters for potentiostatic Pulse technique

### exp_ec_ramp
        Table type: BASE TABLE
        Comment: technique specific parameters for a potential ramp or linear sweep voltammetry (LSV)

### exp_ec_techniques
        Table type: BASE TABLE
        Comment: Stores implemented ec techniques, necessary to guarantee a correct storage of technique specific parameters. This is a so-called super/subtype construct.

### exp_icpms
        Table type: BASE TABLE
        Comment: Table storing all ICPMS experiments including calibration, bulk and sfc-icpms experiments

### exp_icpms_analyte_internalstandard
        Table type: BASE TABLE
        Comment: Relationship of analyte and internal standard in icp-ms experiment. Multiple relationships can be handled, also multiple analytes for one internal standard and vice versa.

### exp_icpms_batch_expanded
        Table type: VIEW
        Comment: VIEW

### exp_icpms_calibration_params
        Table type: BASE TABLE
        Comment: Stores parameter for each analyte internal standard pair in a calibration set as defined in table exp_icpms_analyte_internalstandard.

### exp_icpms_calibration_set
        Table type: BASE TABLE
        Comment:

### exp_icpms_integration
        Table type: BASE TABLE
        Comment: all information from integration of icpmds data integration

### exp_icpms_integration_expanded
        Table type: VIEW
        Comment: VIEW

### exp_icpms_sfc
        Table type: BASE TABLE
        Comment: Parameters specific for sfc-icp-ms experiments

### exp_icpms_sfc_batch
        Table type: BASE TABLE
        Comment: storing experimental parameters for sfc batch experiments

### exp_icpms_sfc_batch_expanded
        Table type: VIEW
        Comment: VIEW

### exp_icpms_sfc_expanded
        Table type: VIEW
        Comment: VIEW

### exp_sfc
        Table type: BASE TABLE
        Comment: parameter of an scanning flow cell experiment. For parameters which can hold more than one value per experiment (for instance multiple gas flows in one experiment) are located in other tables connected to the exp_sfc table via the id_exp_sfc. Same holds true for specific ec parameters (exp_ec) and different ec techniques such as CV, PEIS , GEIS,... with technique specific parameters. All parameters of electrochemical sfc exxperiments can be found combined in one table in the corresponding view "exp_ec_expanded". It is recommended to use this one for selecting data to circumvent multiple join statements in the select query.

### flow_cell_assemblies
        Table type: BASE TABLE
        Comment: holds information on flow cells and additional parts used in the SFC experiment separated into parts above and below the sample. Above the sample (location = top) which is the commonly used SFC method with a flow cell from the top.  Below the sample (location=bottom) especially introduced for the GDE-SFC to support flow of electrolyte or gas from the back of the sample.

### flow_cells
        Table type: BASE TABLE
        Comment: Inventory of flow cells capable to supply gas or electrolyte flow to the sample from top (connected to force sensor) or bottom (connected to stage). Can but does not have to have connections for electrodes.

### flow_electrolyte
        Table type: BASE TABLE
        Comment: parameters of the electrolyte flow(s) within an SFC experiment. Multiple entries for experiments with multiple electrolyte flows (for PTL-SFC)

### flow_gas
        Table type: BASE TABLE
        Comment: parameters of the gas flow(s) within an SFC experiment. Multiple entries for experiments with multiple gas flows

### gamry_set_ca_speed
        Table type: BASE TABLE
        Comment: Relation between CA speed name and corresponding index

### gamry_set_control_mode
        Table type: BASE TABLE
        Comment: Relation between control mode name and corresponding index

### gamry_set_ich_filter
        Table type: BASE TABLE
        Comment: Relation between ich filter name, corresponding index number and frequency value

### gamry_set_ich_range
        Table type: BASE TABLE
        Comment: Relation between ich range name, corresponding index number and maximum acceptable voltage between working and counter electrode

### gamry_set_ie_range
        Table type: BASE TABLE
        Comment: Relation between ie ch range name, corresponding index number and maximum acceptable current between working and counter electrode

### gamry_set_ie_stability
        Table type: BASE TABLE
        Comment: Relation between ie stability name and corresponding index number

### gamry_set_sampling_mode
        Table type: BASE TABLE
        Comment: Relation between sampling mode name and corresponding index number

### gamry_set_vch_filter
        Table type: BASE TABLE
        Comment: Relation between vch filter name, corresponding index number and frequency value

### gamry_set_vch_range
        Table type: BASE TABLE
        Comment: Relation between ich range name, corresponding index number and maximum acceptable voltage between working and counter electrode (?)

### gases
        Table type: BASE TABLE
        Comment: Inventory list of available gases

### is_exp_ec_cv
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_ec_geis
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_ec_ghold
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_ec_gpulse
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_ec_ocp
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_ec_peis
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_ec_phold
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_ec_ppulse
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_ec_ramp
        Table type: BASE TABLE
        Comment: Recquired for so-called super/subtype construct.

### is_exp_icpms_calibration
        Table type: BASE TABLE
        Comment: Recquired for user update of calibration experiment. So that foreign key of  only references to calibration experiments

### isotopes
        Table type: BASE TABLE
        Comment: isotopes used in icpms experiments

### match_exp_sfc_exp_icpms
        Table type: VIEW
        Comment: VIEW

### match_exp_sfc_exp_icpms
        Table type: VIEW
        Comment: VIEW

### peristaltic_pumps
        Table type: BASE TABLE
        Comment: Inventory list of available pump types. Different pumps of the same type are treated as one entry.

### peristaltic_tubings
        Table type: BASE TABLE
        Comment: Inventory list of tubings used. Each tubing gets a new entry with an unique name, by that aging of the tubings can be tracked.

### porous_transport_layers
        Table type: BASE TABLE
        Comment: Inventory list of porous transport layers ready to place in the SFC assembly

### publication_exps
        Table type: BASE TABLE
        Comment: stores entries for all experiments connected to a publication. Creation of table allows for putting all different experiments into the same table no matter on the number of index column. To ensure which multiindex values belong to each other, they must have the same count_exp.

### publications
        Table type: BASE TABLE
        Comment: stores informations of publications using data in the database

### reference_electrodes
        Table type: BASE TABLE
        Comment: Inventory list of reference electrodes

### sample_spots_usage
        Table type: VIEW
        Comment: VIEW

### samples
        Table type: BASE TABLE
        Comment: List of all samples manufactured for and/or used in SFC experiments

### samples_composition
        Table type: BASE TABLE
        Comment: composition  of a sample is defined in weight percentage of the different materials/elements assuming the whole sample has the same composition. If not specifiy in spots_composition.

### sealings
        Table type: BASE TABLE
        Comment: Inventory list of all sealings cutted and used for SFC experiments

### setups_icpms
        Table type: BASE TABLE
        Comment: Inventory list of all inductively coupled plasma mass spectrometry (ICP-MS) setups

### setups_sfc
        Table type: BASE TABLE
        Comment: Inventory list of all scanning flow cell setups

### spots
        Table type: BASE TABLE
        Comment: Inventory list of all spots an samples for SFC measurements. coordinates relative to origin in upper left corner

### spots_auto
        Table type: VIEW
        Comment: VIEW

### spots_composition
        Table type: BASE TABLE
        Comment: composition  of a spot on a sample is defined in weight percentage of the different materials/elements

### users
        Table type: BASE TABLE
        Comment: Inventory list of user of this database. Used to define the user of an experiment or owner of a sample.